### ISSUE TITLE
Highlight error

### ISSUE THREAD

**Issue by cpa-level-it** [Microsoft/vscode-html-languageservice#10]
I discovered an error with the syntax highlighting of HTML code.
If we have a custom tag that starts with *script* followed by a dash ex  `<script-module>`. The text after the *script* part will be highlighted in red and the rest of the file will not be correctly highlighted.

See this screenshot 

![image](https://cloud.githubusercontent.com/assets/9820390/25518147/dc32ed56-2bf2-11e7-9955-a4fbc12aa133.png)

- VSCode Version: 1.12.1
- OS Version: Windows 10

Steps to Reproduce:

1. Type in a tag that starts with *script* followed by a dash eg `<script-module></script-module>`
2. The file isn't correctly highlighted

**Comment by aeschli** [comment]
This issue was moved to textmate/html.tmbundle#68
