### ISSUE TITLE
Link to MDN API docs from intellisense

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode-html-languageservice#12]
_From @Tyriar on February 23, 2016 17:10_

It would be very convenient to have links to API documentation (MDN?) directly within intellisense for HTML, CSS and JS.

![image](https://cloud.githubusercontent.com/assets/2193314/13259640/2210a32e-da0d-11e5-997c-bb76a42c0096.png)

(Currently HTML descriptions is pulled from the spec)

_Copied from original issue: Microsoft/vscode#3358_

**Comment by mjbvz** [comment]
Relevant source: https://github.com/Microsoft/vscode-html-languageservice/blob/f96f320fa67e04c5bfbff33e9c3f9fb49ad611a3/src/parser/htmlTags.ts

**Comment by erikadoyle** [comment]
Here's a way to grab the full directory of MDN's HTML reference:

https://developer.mozilla.org/en-US/docs/Web/HTML/Element$children?expand

By pulling that down, you can query the JSON for individual tag summaries and page URLs. FYI the payload also includes localized pages, so you'll want to account for that in your query.

**Comment by connorshea** [comment]
It may be a better idea to use the [browser-compat-data](https://github.com/mdn/browser-compat-data) repo to find documentation links for each HTML element. You can find the full list of elements at https://github.com/mdn/browser-compat-data/tree/master/html/elements

The BCD is already used by the CSS language server and has been proposed to be used in #22 and #30.

**Comment by octref** [comment]
Re @connorshea, this is something I talked to Mozilla about and look forward to adding. We'll most likely use mdn/data instead of mdn/browser-compat-data for this, and start from CSS.

**Comment by atopal** [comment]
That's really awesome @octref! Many thanks for this. I was wondering if we could add a URL parameter, so we can see on the MDN side when requests come from this? It helps us justify spending time on our "make MDN content available outside of MDN" efforts when we can demonstrate usage and we can optimize content for this usage in the future. Either way: really happy to see this :)
