### ISSUE TITLE
Use `attr="$0"` instead of `attr="$1"` as completion insert text

### ISSUE THREAD

**Issue by johnsoncodehk** [microsoft/vscode-html-languageservice#121]
Downstream issue: https://github.com/johnsoncodehk/volar/issues/949

> IntelliSense initially doesn't work inside the argument of a Vue directive, but after placing the cursor outside the double quotes and back in again, IntelliSense works. (See previous screencast.)

This is because completion insert text is `@click="$1"`, if change to `@click="$0"` it's working good in vscode.

**Comment by aeschli** [comment]
We use '$1' as we want to enter snippet mode when the completion is accepted: The snippet mode comes with two positions: $1 inside the attribute and $0 as the end position at the end of the  insertion string `$0` is the final position to go when leaving the snippet mode (e.g. on tab) and is optional. If not set it is put at the end of the insertion string.)

So we don't want to change that.

BTW, in HTML I get proposals for attribute value inside the quotes: 
![Peek 2022-03-18 17-38](https://user-images.githubusercontent.com/6461412/159045295-42128e33-8134-4ae1-9bec-1f86f55e19b5.gif)

**Comment by johnsoncodehk** [comment]
@aeschli could we detect only enter snippet mode when the accept attribute has available value proposals?

For example, give `$1` when select `type` on `input` tag, give `$0` when select `@vue-event` on `HelloWorld` tag.

**Comment by aeschli** [comment]
The cursor is put between the quotes so a property value can be filled in, either by typing or by completion. That's IMO the logical next step when completing a property and is unrelated whether there are completions available or not.
