### ISSUE TITLE
HTML document formatter doesn't indent nested `<menu>` tags

### ISSUE THREAD

**Issue by gridlocdev** [microsoft/vscode-html-languageservice#135]
The [**`<menu>`**](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/menu) element is a semantic alternative to `<ul>`, but nested menu tags are not indented appropriately using VSCode's default HTML formatter.

> Before formatting the document/selection, with manual indents inserted

![image](https://user-images.githubusercontent.com/60323737/191872626-4b87f4b1-108b-4d7d-93e5-6157c04a2017.png)

> After formatting document/selection

![image](https://user-images.githubusercontent.com/60323737/191872711-efeaf5d8-3a89-455f-880e-033fb91da59b.png)

> After formatting, when the `<menu>` is replaced with `<ul>`

![image](https://user-images.githubusercontent.com/60323737/191872807-634457b2-3a71-4be1-9818-8fd0e21fbe7a.png)

**Comment by abu-co** [comment]
The patched version of `js-beautify` was copied over to this repo in #168, and I think the formatting is no longer incorrect in the latest version of VS Code... so I suppose this issue has been resolved now?

**Comment by gridlocdev** [comment]
> The patched version of `js-beautify` was copied over to this repo in #168, and I think the formatting is no longer incorrect in the latest version of VS Code... so I suppose this issue has been resolved now?

I've done a brief bit of testing, and can confirm that this issue has been fixed in the latest release. Thanks for following up!
