### ISSUE TITLE
Are Typescript types available?

### ISSUE THREAD

**Issue by jonathanstanley** [microsoft/vscode-html-languageservice#136]
I'd like to create an object containing attributes for an element (`<button>`, `<div>`, etc).

for example:
```typescript

let myButton: ButtonAttributes = {
id:"My Button",
disabled:false,
"aria-disabled":false,
tabIndex:0,
}
```

Note: I don't want [HTMLButtonElement from lib.dom.d.ts](https://github.com/microsoft/TypeScript/blob/d0bfd8caed521bfd24fc44960d9936a891744bb7/lib/lib.dom.d.ts#L6121).
1. HTMLButtonElement renames some of the attributes (ex: `aria-disabled` is renamed to `ariaDisabled`)
2. [vscode-html-languageservice descriptions are MUCH better](https://github.com/microsoft/vscode-html-languageservice/blob/bc98617196b13825f33e9bf29663cc76c64ecbad/src/languageFacts/data/webCustomData.ts#L2663).

So my question:
Has anyone converted your [JSON](https://github.com/microsoft/vscode-html-languageservice/blob/bc98617196b13825f33e9bf29663cc76c64ecbad/src/languageFacts/data/webCustomData.ts) to typescript type declarations? (ex: I couldn't find anything here or on [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped))

Any help appreciated.

**Comment by aeschli** [comment]
I'm not aware of such d.ts files. A
