### ISSUE TITLE
the `html.customData` configuration does not work in vue files.

### ISSUE THREAD

**Issue by 643104191** [microsoft/vscode-html-languageservice#160]
# workspace setting.json
```json
{
  "html.customData": ["./.vscode/data-token.json"]
}
```
# data-token.json
```json
{
  "version": 1.1,
  "globalAttributes": [
    {
      "name": "data-token",
      "description": "def token for submit"
    }
  ]
}
```
# It works well in html files.
![image](https://user-images.githubusercontent.com/27074730/236595714-df344b3c-9472-45e2-8753-24b3fbf75dc2.png)
# But it does not work in vue files.
![image](https://user-images.githubusercontent.com/27074730/236595781-8133ae0b-dab3-4fda-b4bc-35b738db3d96.png)

# Do I need other configurations to make `html.customData` configuration work in vue files?

**Comment by aeschli** [comment]
You need to file this request against the vue extension.
