### ISSUE TITLE
Razor formatting issue with the at sign (@)

### ISSUE THREAD

**Issue by vudzero** [microsoft/vscode-html-languageservice#179]
Hi,

Not sure if it's the right place but I have an issue with the html formatting of razor code. The html fortmatter does not seems to handle at signs (@) properly when used as a prefix of an attribute name.

What is expected
<img width="269" alt="image" src="https://github.com/microsoft/vscode-html-languageservice/assets/2973549/a71f9251-42eb-42da-ae77-124aad20fc47">
 
What I get after formatting
<img width="273" alt="image" src="https://github.com/microsoft/vscode-html-languageservice/assets/2973549/8cb40676-09cf-494e-b00b-0c619a454a2b">

I'm using the `"html.format.wrapAttributes": "force-expand-multiline",` options

I'm willing to investigate if someone can point me where to look at

Thanks!

**Comment by aeschli** [comment]
The HTML language server is intended for HTML. It can work for HTML templating languages, but there's no guarantee for it.
We use [beautifyjs](http://jsbeautifier.org/) as the underlying HTML formatter. You can try to file the issue there.

**Comment by vudzero** [comment]
Thanks for your answer!

Would you happen to know why it does work in the beautifyjs playground but not un VSCode?

![image](https://github.com/microsoft/vscode-html-languageservice/assets/2973549/bf31fbce-fae6-4574-b613-850780f3bf7f)

![image](https://github.com/microsoft/vscode-html-languageservice/assets/2973549/55ddf042-bba1-46e7-9259-5c4620fb57ed)

**Comment by aeschli** [comment]
I see you are in a `Razor` file. Is the editor language mode `Razor`? You can see that in the status bar.

In my reply I assumed the editor was in HTML mode.

Out-of-the box, VS Code does not provide a formatter for Razor files. It comes from an extension. You have to file the issue against that extension. https://marketplace.visualstudio.com/items?itemName=ms-dotnettools.csharp is the extension that also covers Razor.
