### ISSUE TITLE
Provide intelliense for html symbol entities like &Eacute

### ISSUE THREAD

**Issue by auchenberg** [Microsoft/vscode-html-languageservice#20]
From twitter, https://twitter.com/ActionNgr:

Please could you do INtelliSense for html symbol entities like &Eacute; in your next update release.

**Comment by aeschli** [comment]
That got added in the December release: https://code.visualstudio.com/updates/v1_19#_languages
![image](https://user-images.githubusercontent.com/6461412/35430458-a18b0924-0278-11e8-8f57-ab96615bd86d.png)

If something is missing, please add steps.

@auchenberg I couldn't find the tweet to reply, looks like that's the wrong userId

**Comment by auchenberg** [comment]
@aeschli It was a private DM on our @code account. I've asked the reporter to give it a look.
