### ISSUE TITLE
Use MDN data to power the HTML language server

### ISSUE THREAD

**Issue by auchenberg** [Microsoft/vscode-html-languageservice#22]
I just had a chat with the MDN team, and they have published a NPM module that enables tools to take advantage of the detailed MDN data.

We should explore using https://github.com/mdn/browser-compat-data to power this language server

**Comment by aeschli** [comment]
Thanks for the pointer.
From how I understand it this provides data which html element and attributes are supported in which browsers.

**Comment by auchenberg** [comment]
Yes, and I would assume it could be the foundation for which HTML tags and attributes that exist too @aeschli. No need to maintain our own list, if we can pull it from MDN that get's maintained by the community.

**Comment by octref** [comment]
There's no concrete todo here. What we can do largely depends on what mdn/browser-compat-data and mdn/data have. For examples, `events` are not in either repo yet: https://github.com/mdn/browser-compat-data/issues/935.

**Comment by Elchi3** [comment]
Compat data for HTML elements and their attributes is available, though: https://github.com/mdn/browser-compat-data/tree/master/html/elements

**Comment by octref** [comment]
@Elchi3 Yeah, that will be done as part of https://github.com/Microsoft/vscode-html-languageservice/issues/30. What I meant by closing is now it comes down to which part of HTML data is available and ready to be consumed by the HTML language service. That will be tracked in an issue-by-issue basis. For example, events, tags, attributes, aria, etc.

**Comment by Elchi3** [comment]
Thanks @octref, subscribing to #30 then :)
