### ISSUE TITLE
provide validation

### ISSUE THREAD

**Issue by harkue** [microsoft/vscode-html-languageservice#26]
How can i do html vadlidation with eslint?

**Comment by aeschli** [comment]
Sorry, please explain more what this is about. Linting JavaScript inside HTML?

**Comment by harkue** [comment]
I was trying to do this:  In vscode-html-languageservice project
1. add import in **htmlLanguageService.ts**  and add a function in class  **LanguageService** 
import { doValidation, createLintEngine } from './services/htmlValidation';

doValidation(document: TextDocument): Diagnostic[];

2.  add a file named htmlValidation.ts in src/services/
`import { CLIEngine, ESLintError } from 'eslint';
import { configs } from 'eslint-plugin-vue';
import { TextDocument, Diagnostic, Range, DiagnosticSeverity } from 'vscode-languageserver-types';

function toDiagnostic(error: ESLintError): Diagnostic {
  const line = error.line - 1;
  const column = error.column - 1;
  const endLine = error.endLine ? error.endLine - 1 : line;
  const endColumn = error.endColumn ? error.endColumn - 1 : column;
  return {
    range: Range.create(line, column, endLine, endColumn),
    message: error.message,
    source: 'ux-language-server',
    severity: error.severity === 1 ? DiagnosticSeverity.Warning : DiagnosticSeverity.Error
  };
}

export function doValidation(document: TextDocument, engine: CLIEngine): Diagnostic[] {
  const rawText = document.getText();
  // skip checking on empty template
  if (rawText.replace(/\s/g, '') === '') {
    return [];
  }
  const text = rawText
    .replace(/ {10}/, '<template>')
    .replace(/\s{11}$/, '</template>'); // TODO: replace the last 11 consecutive spaces
  const report = engine.executeOnText(text, document.uri);

  return report.results[0]
    ? report.results[0].messages.map(toDiagnostic)
    : [];
}

export function createLintEngine() {
  return new CLIEngine({
    useEslintrc: false,
    ...configs.base,
    ...configs.recommended
  });
}
`
3. add dependencies in package.json

"eslint": "^4.19.1",
"eslint-plugin-vue": "^4.5.0",


4. build and exact a htmlLanguageService.js as lib script used in another project named mylang (syntax similar with vue)

5. doValidation in mylang project use htmlLanguageService.

6. it wouldn't work, and it caught an exception when loading the worker, and no further reason.

I was wondering that the eslint lib was packed in the monaco plugin, and it couldn't launch the worker.

how can i fix this problem?

**Comment by aeschli** [comment]
ok, I see. Yes, correct `vscode-html-languageservice doesn't provide validation.
PR are welcome.

**Comment by harkue** [comment]
@aeschli ok, thanks

**Comment by bbougot** [comment]
+1 Really need this feature.

**Comment by trevorade** [comment]
Chiming in as well.  It would be helpful to show errors for things like mix-matched HTML tags or void tags with incorrect closing tags.

**Comment by aeschli** [comment]
Closing as out-of-scope
