### ISSUE TITLE
Insert warning on deprecated / obsolete HTML Elements

### ISSUE THREAD

**Issue by lannonbr** [microsoft/vscode-html-languageservice#30]
As a feature that could be implemented after #22, It would be neat to either display a warning / error on html elements which are deprecated (blink, marquee, etc.).

In MDN's browser-compat-data repo, html elements have a `deprecated` property on them (For instance, here on the [blink](https://github.com/mdn/browser-compat-data/blob/master/html/elements/blink.json#L55) tag, so if the language server switches to use MDN's data, this could be a fairly quick feature to implement.

**Comment by octref** [comment]
Currently we only have this inside our code:

![image](https://user-images.githubusercontent.com/4033249/51134526-b7824780-17ec-11e9-96d0-2a9b9de8f1d4.png)

But MDN does have relevant info, for example https://developer.mozilla.org/en-US/docs/Web/HTML/Element/menuitem. After finishing up #44 I can look into this.

**Comment by aeschli** [comment]
Validation is not planed.
