### ISSUE TITLE
Provide an option to allow HTML formatter insert newlines after specified tags

### ISSUE THREAD

**Issue by tommai78101** [Microsoft/vscode-html-languageservice#32]
There is an option in VS Code that it current supports inserting newlines:

```
  "html.format.extraLiners": "head, body, /html",
```

However, that option is only for inserting newlines **before** the specified tags. It currently doesn't support inserting newlines **after** specified tags when formatting HTML documents.

Is it okay to add an option to specify tags to insert newlines after?

**Comment by aeschli** [comment]
We use [beautifyjs](http://jsbeautifier.org/) as the underlying HTML formatter. Would you mind filing this request directly against https://github.com/beautify-web/js-beautify ?

**Comment by tommai78101** [comment]
Thanks again for letting me know.
