### ISSUE TITLE
Feature Request: Allow disabling of angular 1.* HTML options

### ISSUE THREAD

**Issue by Brocco** [Microsoft/vscode-html-languageservice#5]
This issue is related directly to Microsoft/vscode#17613 but the code lives here in this repo.

It would be nice to have an option to turn on/off some of the tagProviders via settings.

**Comment by scniro** [comment]
So this _is_ an issue? I've been on a grand old goosechase to get this out of here. I think it's a bug per my discoveries in https://github.com/Microsoft/monaco-html/issues/3

Has there been any progress on this? @Brocco have you found a work around?

**Comment by Brocco** [comment]
I have not had any issues since the setting was addressed in the issue I referenced above. I apologize for not closing this issue previously.

The setting to turn off these helpers is:

```
"html.suggest.angular1": false,
```
