### ISSUE TITLE
Events API

### ISSUE THREAD

**Issue by goatandsheep** [Microsoft/vscode-html-languageservice#51]
Is there a way to show events fired?

**Comment by aeschli** [comment]
What kind of events?

**Comment by goatandsheep** [comment]
@aeschli sorry for my lack of clarity. I mean for events fired by the elements, particularly custom elements

**Comment by aeschli** [comment]
Please give some examples... Maybe a small sample code what you expect to see (hovers, code completion...)

**Comment by goatandsheep** [comment]
I think that [@event](http://usejsdoc.org/tags-event.html) is a great example for how it could be denoted. The hover for jsdoc is really good. I think the hover could either:

* simply have the event in the description of the element
* treat it like an attribute with the name `on<custom-event-name>`

**Comment by aeschli** [comment]
I guess this is about JavaScript/TypeScript then. Still I don't know what exactly you suggest to improve or add. Something for VSCode to show, or a TypeScript language feature?

**Comment by goatandsheep** [comment]
Similar to this issue https://github.com/w3c/webcomponents/issues/776 that addresses displaying details about custom components, I would add to it to show events when writing HTML

**Comment by octref** [comment]
If all you want is `onMyEvent` as an attribute completion, why can't you use the existing `globalAttributes`? https://github.com/Microsoft/vscode-html-languageservice/blob/master/docs/customData.md

**Comment by goatandsheep** [comment]
@octref because the type of input is always function, but what's important about documenting events is not the type of input but the type of data from the event

**Comment by octref** [comment]
We don't do any type-checking diagnostic for HTML attribute value, at least not on the HTML service.

What [Language Feature](https://code.visualstudio.com/api/language-extensions/programmatic-language-features#language-features-listing) exactly do you want for events?

**Comment by aeschli** [comment]
ping @goatandsheep 
Please explain who shuch support for events would look like in the UI. 
Maybe a small sample code along with what you expect to see (hovers, code completion...)

**Comment by goatandsheep** [comment]
@aeschli I was thinking about how when you do event handling in the HTML, your input for an `oncustombind` would be a callback function, so the documentation for an event should be like any other Javascript function, i.e. JsDoc. However, as @octref mentioned, that would be checked in Javascript, not HTML, anyways. So it would likely be enough to simply add `onevent` with a description of the event and the type being `Function`.

It's fine if referring to events in the hovers doesn't require code changes, but we should encourage use and show examples of how it would be used.

**Comment by octref** [comment]
Due to the myriad ways people load their JS it's impossible to check where the value of `myevent="something"` comes from. I don't want Schrodinger's diagnostics for `myevent="window.foo"`, so no.

**Comment by goatandsheep** [comment]
@octref would [this standard for documenting custom elements using jsdocs by @runem](https://github.com/runem/web-component-analyzer#-how-to-document-your-components-using-jsdoc) still require a myriad of ways to diagnose the values?

**Comment by octref** [comment]
You should ask them to generate data of this format: https://github.com/microsoft/vscode-html-languageservice/blob/master/docs/customData.md.

**Comment by goatandsheep** [comment]
@octref thank you for the suggestion! They actually already do generate data of that format, but the format is quite rudimentary as it doesn't let you list events, slots, nor cssprops. I'm thinking, instead of trying to interpret each of the jsdoc tags and every future request that may come, is there a way to just show various tags as hover comments?

**Comment by octref** [comment]
No. Each item's `description` is shown on hover. That's all. Ask them to put whatever they want into the `description`.

**Comment by octref** [comment]
No. Each item's `description` is shown on hover. That's all. Ask them to put whatever they want into the `description`.

**Comment by goatandsheep** [comment]
That's perfect. Thanks @octref !
