### ISSUE TITLE
Add data manager

### ISSUE THREAD

**Issue by KamasamaK** [microsoft/vscode-html-languageservice#53]
Even though it doesn't seem that there is officially support for this, I am using this package and `Microsoft/vscode-css-languageservice` for their well organized and structured data. The CSS package makes it a bit easier by having a [data manger](https://github.com/Microsoft/vscode-css-languageservice/blob/master/src/languageFacts/dataManager.ts), so it would be nice if this package had that as well.

**Comment by aeschli** [comment]
I'd rather not make the data manager API. IMO it adds little benefits, but will cause us work and later when maintaining the API. Keeping it compatible across all versions is costly.
Things like filtering for 'supported In more than one browser' are likely going to be refined soon.

**Comment by octref** [comment]
That manager is internal...Anyway, this will be a bit different because for CSS it's just plain lists, but for HTML there exists tag/attribute/attribute-value inter relationships.

**Comment by KamasamaK** [comment]
@octref I realize that it's not part of a public API, but it's still accessible so I used it. I was inspired by your contribution for d4rkr00t/language-stylus#69 which also used the package's internals, though that was before the manager was created so it's not quite as nice. Nevertheless, I think that contribution showed the value and need for something like this so I thought I'd ask. I can deal with it not being officially supported, and in fact I kind of already implemented my own manager but thought it would be nice to have it internal.

**Comment by aeschli** [comment]
Closing as out-of-scope
