### ISSUE TITLE
If attribute is named "data", an additional attribute called "data-" is added.  Bug?

### ISSUE THREAD

**Issue by bkelley13** [microsoft/vscode-html-languageservice#56]
This is odd, if I have an attribute called "data", two items are added to the list of choices: "data" and "data-".  This is the only attribute which I've encountered any issues (our schema has > 1000 attribute names).

![image](https://user-images.githubusercontent.com/3596149/53456333-dfb3b780-39e2-11e9-81fe-f007dda27039.png)

You can replicate using:
{
  "version": 1,
  "tags": [{
    "name": "my-button",
    "description": "My button",
    "attributes": [{
      "name": "data",
      "description": "My button type",
      "values": [
        { "name": "alert-one" },
        { "name": "alert-two" }
      ]
    }]
}]}

Then activate the above as you will, and type:

<my-button |

You will see list of choices including:
data
data-

This seems like a bug to me.

**Comment by octref** [comment]
This is as-designed. VS Code prompts you for `data-` as a completion item. This happens even if you don't have any custom data.
