### ISSUE TITLE
markdown descriptions

### ISSUE THREAD

**Issue by bkelley13** [microsoft/vscode-html-languageservice#57]
If a URL is used in a description, it's clickable in the hover text:
![image](https://user-images.githubusercontent.com/3596149/53589317-f160a080-3b43-11e9-9460-8076061abdef.png)

However, it's not clickable when shown in dropdown of options when typing:
![image](https://user-images.githubusercontent.com/3596149/53589413-25d45c80-3b44-11e9-8f30-59467ac99d09.png)

Also, it would be nice to have a way to hide the URL and show a rich text hot link, aka a markdown or HTML anchor instead of just relying on the full URL.

**Comment by aeschli** [comment]
@octref The request is to also allow markdown descriptions in the custom data.
