### ISSUE TITLE
AMP support

### ISSUE THREAD

**Issue by e-jigsaw** [microsoft/vscode-html-languageservice#62]
I want to write AMP page like standard html5 page with `html-languageservice`.

Spec is maintained in https://github.com/ampproject/amphtml/blob/master/validator/validator-main.protoascii

Is there any way to get in?

Thanks

**Comment by aeschli** [comment]
Code completion and hovers for additional tags can be added through custom data files.
See here https://github.com/microsoft/vscode-html-languageservice/blob/master/docs/customData.md

**Comment by e-jigsaw** [comment]
Thank you for info, I will try later

**Comment by octref** [comment]
There's nothing we can do from html-languageservice side, thus closing. You can use custom data as mentioned above.
