### ISSUE TITLE
Use it outside VSCode

### ISSUE THREAD

**Issue by mtangoo** [microsoft/vscode-html-languageservice#67]
Hi,
We want to use this LS for our in house editor together with the CSS and JSON language servers. Now where is instruction how to do that. We want to use it over Sockets not STDIO.

Sorry if it is already documented somewhere. I could not find it!

**Comment by aeschli** [comment]
@mtangoo The HTML language service is just a library that you can add as a node modules, for example in a language server. You probably are looking HTML language *server*. The code for the server is [here](https://github.com/microsoft/vscode/tree/master/extensions/html-language-features/server) and is part of the VSCode build that you can download.
We don't offer the HTML server as a node module. That's requested here: https://github.com/microsoft/vscode/issues/77582
But there are others that do that.

**Comment by aeschli** [comment]
Closing as the service is available to be used outside.

**Comment by mtangoo** [comment]
@aeschli  thank you!

**Comment by PhaserEditor2D** [comment]
Hi,

I am using the https://github.com/microsoft/monaco-editor in a custom, browser IDE. I need to build the Outline of an HTML file but I don't see how to do it.

I can do it for JavaScript files using code like this:

```
const getWorker = await monaco.languages.typescript.getJavaScriptWorker();
const worker = await getWorker();
const outlineItems = await worker.getNavigationBarItems(uri);
```

However, I don't see the `monaco.languages.html` module exposes an API to get such information. I am using the `monaco.d.ts` file provider by the Monaco source code (I don't see the monaco.d.ts file provided in this repo exposes too much API neither)

What can I do?
