### ISSUE TITLE
"sortable" is not an attribute of <table>

### ISSUE THREAD

**Issue by BMBurstein** [microsoft/vscode-html-languageservice#68]
The attribute `sortable` on the `<table>` tags was considered in an early draft of the HTML 5.1 spec, but was dropped for lack of any supporting implementations. It is no longer even part of the spec.
See for example here https://github.com/w3c/html/commit/3cd9f9cb0003536e961cbcaee34f34a279081a75 and https://stackoverflow.com/questions/41359602/which-web-browsers-support-the-html5-attribute-sortable

**Comment by octref** [comment]
@BMBurstein I used to pull data from https://github.com/w3c/html/blob/master/sections/elements.include. Seems it's gone from there as well so I can update.

**Comment by octref** [comment]
There's a more updated version: https://html.spec.whatwg.org/multipage/indices.html#elements-3

**Comment by octref** [comment]
Actually it comes from our old data. I just deleted it.
