### ISSUE TITLE
When opening MDN link, signal to MDN it's from VS Code

### ISSUE THREAD

**Issue by octref** [microsoft/vscode-html-languageservice#71]
From https://github.com/microsoft/vscode-html-languageservice/issues/12#issuecomment-524852495

The only concern I have is that as a user, I'd want a clean URL that's easily sharable, like:

https://developer.mozilla.org/en-US/docs/Web/CSS/animation

instead of:

https://developer.mozilla.org/en-US/docs/Web/CSS/animation?from=vscode

I'm wondering if we could achieve this through other means. For example setting a user-agent (is this achievable?) when we open external links. Or we could ask MDN to have a client side redirect that cleans up the params.

**Comment by atopal** [comment]
We can add a redirect, but that might be a bit more invasive to the UX than the URL parameter. A referrer header might be an option too (but I'm not sure how technically feasible that is). In case you go with the URL parameter, the default format would be: utm_source=vscode. I'd prefer the URL parameter, but we can accommodate other options too.

**Comment by aeschli** [comment]
No plans for this.
