### ISSUE TITLE
Enable for markdown

### ISSUE THREAD

**Issue by zavr-1** [microsoft/vscode-html-languageservice#74]
Could you sort of enable this stuff for markdown also? HTML is recognised and highlighted in md files.

**Comment by aeschli** [comment]
You want html completions inside markdown? You have to file this against the markdown extension. They can then use this service to provide all proposals

**Comment by zavr-1** [comment]
mate... you work for microsoft not me. i see 5 repos https://github.com/microsoft?utf8=%E2%9C%93&q=markdown&type=&language= here none of which really fit the "markdown extension" description. it's kind of your job to at least point me in the right direction. it's called "service" friend shame you don't get internal briefings on that. shows how much you care about your users...
