### ISSUE TITLE
don't open attributes for boolean 

### ISSUE THREAD

**Issue by zavr-1** [microsoft/vscode-html-languageservice#75]
if i have a boolean attribute and type <hello worl...d> where d will be suggested, and i press enter, the attribute is opened like <hello world=""> but I don't want ="" because it's a boolean attribute (values = [true, false]). can you disable that

**Comment by aeschli** [comment]
@zavr-1 Can you add a code snippet?

**Comment by zavr-1** [comment]
@aeschli ok e.g.,
```html
<my-element d-flex align-items-center />
```
```json
"globalAttributes": {
      "name": "align-items-start",
      "values": [
        true,
        false
      ],
      "description": "Bootstrap Utility\nhttps://getbootstrap.com/docs/"
    },
```
these are some bootstrap utils. 
![d-flex](https://user-images.githubusercontent.com/21156791/69510785-3be64080-0f4f-11ea-84aa-675e9212a590.gif)
like i don't even have esc cape it's freaking annoying

**Comment by aeschli** [comment]
@zavr-1 Instead of specifying `"values": [ true, false ]`, can you try to use `"valueSet": "v"` ?

@octref Please advise...

**Comment by zavr-1** [comment]
@aeschli oh yeah thanks man that worked! I suppose you can close this but probably needs to be documented somewhere...
