### ISSUE TITLE
Document supported settings

### ISSUE THREAD

**Issue by AmjadHD** [microsoft/vscode-html-languageservice#77]
I can't find a reference to the list of settings that work with this language server (and not vscode specific).

**Comment by aeschli** [comment]
This is the repo of the service (not server). You find the supported types in the d.ts files published with the node moudle or in source code:
- serviceoptions: https://github.com/microsoft/vscode-html-languageservice/blob/da1d9b3d9fc3e62896f76a2d930cc0ebea7d3fa7/src/htmlLanguageTypes.ts#L221
- formatter settings: https://github.com/microsoft/vscode-html-languageservice/blob/da1d9b3d9fc3e62896f76a2d930cc0ebea7d3fa7/src/htmlLanguageTypes.ts#L9
as well as service

**Comment by AmjadHD** [comment]
these aren't vscode specific ?

**Comment by aeschli** [comment]
Not sure what you mean by VSCode specific. The html-languageservice API can be used independently of VSCode.
