### ISSUE TITLE
Support for .html.eex and .html.leex files

### ISSUE THREAD

**Issue by mlesin** [microsoft/vscode-html-languageservice#83]
Please add support (at least) for closing and renaming files while editing Elixir Phoenix (Live) templates, files with extensions like .html.eex and .html.leex
These files have script parts inside, therefore I can't just say they are in HTML format - I will loose all auto completion related to elixir then.

**Comment by panoply** [comment]
From my knowledge, html-language-features can be extended to other templating languages outside of HTML via the client (as an example, handlebars does this). I have stumbled across a couple of solutions that might help you in supporting HTML smarts in non-html files or files that infuse consumer facing code with HTML (eg: templating engines)

1. You can try grammar injections, which will extend upon HTML itself, the downside would be `<%=` (eex) delimiters/tags would considered apart of the HTML Grammar, which is likely to cause headaches for some users, but should suffice for the vast majority.

2. Using an [embedded-language-service](https://github.com/microsoft/vscode-extension-samples/tree/master/lsp-embedded-language-service) makes it somewhat easily extend support for HTML IntelliSense in `.eex` files by feeding the textdocument to this service. This is the recommended way (from my understanding) of how one should achieve what you're looking to do.

3. You could load the HTML Language Features which ships with vscode by default on the client side. I have not really seen anyone do this in the wild but it does work, an example of how you can do that: 

```js

// reads the pkgjson file og html-language-features
  const getPkgJson = extension => {
    const read = fs.readFileSync(path.join(extension, 'package.json')).toString()
    try {
      return JSON.parse(read).main
    } catch (e) {
      console.log(`Problems reading ${extension}: ${e}`)
      return {}
    }
  }

  /**
   * HTML Features
   */
  const { extensionPath } = extensions.getExtension('vscode.html-language-features')
  const extension = path.join(extensionPath, 'server')
  const module = path.join(extension, getPkgJson(extension))

  /**
   * HTML Server Options
   * @type { import("vscode-languageclient").ServerOptions }
   */
  const server = {
    run: {
      module,
      transport: 1
    },
    debug: {
      module,
      transport: 1
    }
  }

  /**
   * HTML Client Options
   *
   * @type { import("vscode-languageclient").LanguageClientOptions }
   */
  const client = {
    documentSelector: [
      {
        scheme: 'file',
        language: 'eex'
      },
      {
        scheme: 'untitled',
        language: 'eex'
      }
    ],
    synchronize: {
      configurationSection: [
        'html',
        'css',
        'javascript'
      ]
    },
    initializationOptions: {
      dataPaths: [],
      embeddedLanguages: {
        css: true,
        javascript: true
      }
    }
  }

  /**
   * HTML Language Client
   */
  const html = new LanguageClient('html', server, client)
```

Hope it helps.

**Comment by aeschli** [comment]
We have https://github.com/microsoft/vscode/issues/49210 to make it easier to inherit HTML features for HTML like languages
