### ISSUE TITLE
Enable parsing inside of some script tags to find the right node

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode-html-languageservice#97]
I'm currently moving over Emmet to use this repo for HTML parsing, but encountered this issue: https://github.com/microsoft/vscode/issues/36905

However, this issue also affects linked editing, since linked editing isn't working inside of those types of script nodes.

I tried manually reparsing the document recursively within those nodes as a workaround:

```
when we encounter node with script tag and the right attribute (see issue):
  get substring starting from end of start script tag to start of end script tag
  make a new document out of that substring
  run the parse method again to find the right node within that subsection
```
 
But, this strategy wasn't working: the offsets returned were local to that subsection, and findNodeAt returned the wrong result.

I think it would make more sense to incorporate this into the parse() algorithm itself.

**Comment by aeschli** [comment]
I this about `type="text/template"` ?
```
<script type="text/template" id="user_dropdown_template">
    <div class="ui label">Tagged users</div>
    <div class="ui dropdown" id="user_dropdown">
        <div class="text"></div>
        <i class="dropdown icon"></i>
    </div>
</script>
```

From what I understand, type="text/template" doesn't imply that there is HTML syntax inside. It can be anything. It all depends on the templating language what the actual syntax is. 

The HTML parser should not try to guess anything here. For the HTML parser this is just an a script element.

What you have tried should work. You just needs to map the offsets. Alternative look at what we do with embedded CSS and JavaScript: https://code.visualstudio.com/api/language-extensions/embedded-languages#language-services-sample

**Comment by aeschli** [comment]
Closing as the HTML parser should not try to guess anything here.
